PATH:
  TRAIN_PATH: "/home/ykwei/MCMT-SU/mcmt/dataset/train"
  VALID_PATH: "/home/ykwei/MCMT-SU/mcmt/dataset/validation"
  OUTPUT_PATH: "/home/ykwei/MCMT-SU/mcmt/mct_model/checkpoints"

DEVICE:
  TYPE: "cuda"
  GPU: 1

MCT:
#  FEATURE_DIM: 512
  FEATURE_DIM: 2048
  LEARNING_RATE: 0.001   # 0.001
  WEIGHT_DECAY: 0.3   # 0.3
  EPOCHS: 10
  BATCH_SIZE: 16   # 128 64
  RW: True
  WEIGHT: "/home/ykwei/MCMT-SU/mcmt/mct_model/checkpoints/None_3.pth"
  